spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: M2Cc4SSIRJVXS5hGhdnaN2FJV004PtIM
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt




  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    show-sql: true

selmag:
  services:
   catalogue:
       uri: http://localhost:8081
       registration-id: keycloak

logging:
  level:
    org.springframework.security: DEBUG
    sql: info
