spring:
  security:
    user:
      name: service_user
      password: '{noop}password'
      roles:
        - SERVICE



  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: catalogue
    password: catalogue
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    show-sql: true

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    sql: info
